# Generated by Django 4.2.27 on 2026-01-21 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(default='pageview', max_length=20)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('referrer', models.CharField(blank=True, default='', max_length=512)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('read_ratio', models.FloatField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='content.article')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'created_at'], name='content_eve_kind_d748e4_idx'), models.Index(fields=['article', 'created_at'], name='content_eve_article_92f5b9_idx')],
            },
        ),
    ]
