# Generated by Django 4.2.27 on 2026-01-25 07:32

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_trigram_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='curatedmodule',
            new_name='content_cur_placeme_fee187_idx',
            old_name='content_cur_place_8b613e_idx',
        ),
        migrations.RenameIndex(
            model_name='curatedmodule',
            new_name='content_cur_placeme_365f13_idx',
            old_name='content_cur_place_4f86a6_idx',
        ),
        migrations.RenameIndex(
            model_name='curatedmoduleitem',
            new_name='content_cur_module__6a5f42_idx',
            old_name='content_cur_module_9bbf7e_idx',
        ),
        migrations.AlterField(
            model_name='article',
            name='search_tsv',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
